// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.build/**",
      "**/.wrangler/**",
      // Local session-tool scratch, not part of the project.
      ".remember/**",
      // Generated by `wrangler types`; regenerate rather than edit.
      "worker/worker-configuration.d.ts",
      // Generated by npm run build:companion.
      "worker/public/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Unused values are a bug signal, but a leading underscore is the documented opt out.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // Every promise here either awaits or is handed to waitUntil. Floating ones lose errors.
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      // `any` erases the type guarantees this project relies on for its security invariants.
      "@typescript-eslint/no-explicit-any": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  {
    // Tests reach into loosely typed protocol payloads and D1 result rows on purpose.
    files: ["**/test/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  {
    files: ["**/*.mjs", "**/*.config.ts"],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    // The Zoho conformance probe is a Node CLI run by hand against the client's mailbox (M0 Task 0.7).
    files: ["scripts/probe/**/*.mjs"],
    languageOptions: { globals: { fetch: "readonly", URLSearchParams: "readonly", process: "readonly" } },
  },
  {
    // The companion bundler is a Node build script (M6 Task 6.6); its one console line is its output.
    files: ["companion/scripts/**/*.mjs"],
    languageOptions: { globals: { URL: "readonly", console: "readonly", process: "readonly" } },
    rules: { "no-console": "off" },
  },
  prettier,
);
