import { createHash } from "node:crypto";
import { readFile, lstat } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { resolve } from "node:path";
const exec = promisify(execFile);
export type Input = { path: string; bytes: Buffer };
export function hashInputs(inputs: Input[]): string {
  const hash = createHash("sha256");
  for (const f of [...inputs].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))) {
    const path = Buffer.from(f.path);
    hash.update(String(path.length) + ":");
    hash.update(path);
    hash.update(String(f.bytes.length) + ":");
    hash.update(f.bytes);
  }
  return hash.digest("hex");
}
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value !== null && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value)
        .sort(([a], [b]) => (a < b ? -1 : 1))
        .map(([k, v]) => [k, canonical(v)]),
    );
  return value;
}
export function canonicalConfig(input: Record<string, unknown>): string {
  const copy = structuredClone(input);
  const vars = copy.vars;
  if (vars && typeof vars === "object" && !Array.isArray(vars)) {
    const record = vars as Record<string, unknown>;
    delete record.BUILD_ID;
    for (const k of Object.keys(record))
      if (/SECRET|TOKEN|PASSWORD|KEKS|HMAC/i.test(k)) throw new Error("secret values cannot enter build identity");
  }
  return JSON.stringify(canonical(copy));
}
export const identitySource = (id: string) =>
  `// Generated by qualification build-id; no other code is allowed in this file.\nexport const BUILD_ID = "${id}";\n`;
const production = (path: string) =>
  /^(worker\/src\/|shared\/src\/|worker\/migrations\/)/.test(path) ||
  [
    "package.json",
    "package-lock.json",
    "tsconfig.base.json",
    "shared/package.json",
    "worker/package.json",
    "shared/tsconfig.json",
    "worker/tsconfig.json",
    "worker/wrangler.jsonc",
  ].includes(path);
export async function computeBuildId(root: string, config: Record<string, unknown>): Promise<string> {
  root = resolve(root);
  const names = (await exec("git", ["ls-files", "-z"], { cwd: root })).stdout.split("\0").filter(production);
  const dirty = (await exec("git", ["diff", "HEAD", "--name-only", "-z"], { cwd: root })).stdout.split("\0");
  const untracked = (
    await exec("git", ["ls-files", "--others", "--exclude-standard", "-z"], { cwd: root })
  ).stdout.split("\0");
  if (untracked.some(production) || dirty.some((p) => production(p) && p !== "worker/src/build-identity.ts"))
    throw new Error("dirty production input");
  const inputs: Input[] = [];
  for (const path of names) {
    const full = resolve(root, path);
    if (!(await lstat(full)).isFile()) throw new Error("nonregular production input");
    let bytes = await readFile(full);
    if (path === "worker/src/build-identity.ts") {
      if (
        !/^\/\/ Generated by qualification build-id; no other code is allowed in this file\.\nexport const BUILD_ID = "(?:unqualified|[a-f0-9]{64})";\n$/.test(
          bytes.toString(),
        )
      )
        throw new Error("modified identity template");
      bytes = Buffer.from(identitySource("unqualified"));
    }
    if (path === "worker/wrangler.jsonc") bytes = Buffer.from(canonicalConfig(config));
    inputs.push({ path, bytes });
  }
  return hashInputs(inputs);
}

if (process.argv[1]?.endsWith("/build-id.ts")) {
  const { fileURLToPath } = await import("node:url");
  if (resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try {
      if (process.argv.length !== 4 || process.argv[2] !== "--config")
        throw new Error("private effective config required");
      const { readPrivateJson } = await import("./private-files.ts");
      const { z } = await import("zod");
      const { writeFile } = await import("node:fs/promises");
      const config = z.record(z.string(), z.unknown()).parse(await readPrivateJson(process.argv[3]!));
      const root = fileURLToPath(new URL("../../", import.meta.url));
      const id = await computeBuildId(root, config);
      await writeFile(resolve(root, "worker/src/build-identity.ts"), identitySource(id));
      process.stdout.write(id + "\n");
    } catch {
      process.stderr.write(
        "build identity refused; clean production inputs and a private effective config are required\n",
      );
      process.exitCode = 1;
    }
  }
}
