"""Reproduce immutable SQL fixtures; inventory is not execution coverage."""

import csv
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
BASELINE = "6e78bc548c97bbe5194e3f780c717e5519930c1a"
INVENTORY = ROOT / "docs/superpowers/reviews/2026-09-13-plan-5-writer-inventory.csv"


def render() -> str:
    with INVENTORY.open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    identities = {(r["file"], r["line"], r["sha256"]) for r in rows}
    if len(rows) != 136 or len(identities) != 136:
        raise ValueError("legacy inventory incomplete")
    sources: dict[str, str] = {}
    for row in rows:
        if row["file"] not in sources:
            sources[row["file"]] = subprocess.check_output(
                ["git", "show", f"{BASELINE}:{row['file']}"], cwd=ROOT
            ).decode()
        source = sources[row["file"]]
        lines = source.splitlines(keepends=True)
        line = int(row["line"]) - 1
        if line < 0 or line >= len(lines):
            raise ValueError("legacy source location mismatch")
        start = sum(map(len, lines[:line]))
        found = source.find(row["sql"], start)
        if not start <= found < start + len(lines[line]):
            raise ValueError("legacy source location mismatch")
        if hashlib.sha256(row["sql"].encode()).hexdigest() != row["sha256"]:
            raise ValueError("legacy source mismatch")
    return (
        "// Generated by capture_writer_corpus.py from immutable baseline "
        + BASELINE
        + ".\nexport const legacyWriterCorpus = "
        + json.dumps(rows, indent=2)
        + " as const;\n"
    )


def main() -> None:
    output = ROOT / "worker/test/fixtures/legacy-writer-corpus.ts"
    content = render()
    if sys.argv[1:] == ["--check"]:
        # Compare after repository formatting without rewriting the fixture.
        result = subprocess.run(
            ["npx", "--no-install", "prettier", "--stdin-filepath", str(output)],
            input=content,
            text=True,
            capture_output=True,
            cwd=ROOT,
            check=True,
        )
        if output.read_text() != result.stdout:
            raise ValueError("legacy corpus stale")
        return
    if sys.argv[1:]:
        raise ValueError("usage: capture_writer_corpus.py [--check]")
    output.write_text(content)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, subprocess.SubprocessError):
        sys.exit("legacy corpus verification failed; check the pinned source")
