#!/usr/bin/env node
// Prints the Worker's secrets as JSON on stdout, for `wrangler secret bulk` to read from a pipe, so
// they never touch disk outside .env. With --ensure-keys, first appends any missing generated keys
// (ZMC_TOKEN_KEK_K1, ZMC_STATE_HMAC_KEY, ZMC_CSRF_HMAC_KEY) to .env, so redeploys reuse them.
import { appendFileSync } from "node:fs";
import { ENV_FILE, readEnvFile } from "./env-file.ts";
import { generatedKeyLines, workerSecrets } from "./lib.ts";

let env = readEnvFile();
if (process.argv.includes("--ensure-keys")) {
  const lines = generatedKeyLines(env);
  if (lines.length) {
    appendFileSync(
      ENV_FILE,
      "\n# zoho-mail-mcp Worker keys (generated by scripts/deploy/secrets.ts)\n" + lines.join("\n") + "\n",
    );
    env = readEnvFile();
  }
}
process.stdout.write(JSON.stringify(workerSecrets(env)));
